Repository eccentriccoder01/Spamlyser, pull requests merged in 2025-09, with the labels that each got.

#53 Update README with new features (dark mode, pytest, Docker, CI/CD)
  README.md
Labels: documentation, enhancement, good first issue, level 3, gssoc25

#59 Enhanced Code of Conduct with GIFs, badges, and emojis for better UX
  CODE_OF_CONDUCT.md
Labels: documentation, level 1, gssoc25

#61 Add ONNX export script for DistilBERT model
  optimize_model.py
Labels: enhancement, level 3, gssoc25

#62 Onnx integration
  app.py
  optimize_model.py
Labels: enhancement, level 3, gssoc25

#64 Smart preprocessing feature
  app.py
  smart_preprocess.py
Labels: level 3, gssoc25

#74 Refactor
  app.py
  csv/multiclass_sample_data.csv
  csv/sample_data.csv
  imgs/App.jpeg
  imgs/Results.jpeg
  imgs/SpamlyserLogo.png
  imgs/gssoc logo.png
  models/ensemble_classifier_method.py
  models/export_feature.py
  models/model_explainer.py
  models/optimize_model.py
  models/simple_explainer.py
  models/smart_preprocess.py
  models/threat_analyzer.py
  models/word_analyzer.py
Labels: level 2, gssoc25
